[target.thumbv8m.main-none-eabihf]
runner = "probe-rs run --chip STM32WBA65RI"

rustflags = [
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv8m.main-none-eabihf"
